# Generated by Django 5.1.6 on 2025-02-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_game_ticket_ticketgame_ticket_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketgame',
            name='game',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='games',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
